### PR TITLE
CIV-6541 Add By court initiative radio button

### PR DESCRIPTION
**Pull request by karthick-mohanasundaram-HMCTS**
**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [x] Screenshot attached for the Evidence of manual testing
- [x] Functional, Smoke and API tests have been run locally
- [x] Full gradle build and run tests with coverage have been completed (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-6541

### Change description ###
Add "By Courts Initiative" radio button to Judge Screen for Judge Makes an Order, Judge Lists for hearing, Order for written representations 

### Testing branch and instruction ###

GA CCD and GA
CIV-6541

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
[6541 SCREENSHOT.docx](https://github.com/hmcts/civil-general-applications/files/10269585/6541.SCREENSHOT.docx)

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
SMOKE
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
- [ ] @automatemm to fix ui test

**Review by pliao-hmcts — APPROVED** [review]

**Review by Azam-Hmcts — APPROVED** [review]

**Pull request closed without merging**
