### PR TITLE
CIV-6284 6558 Update order template

### PR DESCRIPTION
**Pull request by karthick-mohanasundaram-HMCTS**
**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Screenshot attached for the Evidence of manual testing
- [ ] Functional, Smoke and API tests have been run locally
- [x] Full gradle build and run tests with coverage have been completed (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-6284
https://tools.hmcts.net/jira/browse/CIV-6558

### Change description ###
CIV-6558

populate the court location on the order templates

CIV-6558

Update the order templates

### Testing branch and instruction ###

GA, GA CCD
CIV-6284

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Review by pliao-hmcts — APPROVED** [review]

**Comment by karthick-mohanasundaram-HMCTS** [comment]
- [ ] Fix Checkstyle

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
For one of the PR (CIV-6541), backend changes has to go first, followed by CCD
For another PR (CIV-6284), CCD changes has to go first, followed by bankend.
Since both the PRs are merged into one, build is failing for GA and GA CCD

**Review by deepthidoppalapudihmcts — DISMISSED** [review]

**Review by automatemm — APPROVED** [review]

**Review by vasudevganesanhmcts — APPROVED** [review]

**Pull request merged**
