### PR TITLE
CIV-3427 Implement case management category field

### PR DESCRIPTION
**Pull request by karthick-mohanasundaram-HMCTS**
**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [x] Screenshot attached for the Evidence of manual testing
- [x] Functional, Smoke and API tests have been run locally
- [x] Full gradle build and run tests with coverage have been completed (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-3427

### Change description ###
Implement case management category field

### Testing branch and instruction ###
Changes are across GA, GA CCD, Civil, Civil CCD. Branch name is as same as below across all the repos

feature/CIV-3427

https://github.com/hmcts/civil-service/pull/1417
https://github.com/hmcts/civil-ccd-definition/pull/1258
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/316
https://github.com/hmcts/civil-general-applications/pull/523

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
API
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
functional multiparty
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
smoke test

image

**Review by Azam-Hmcts — APPROVED** [review]

**Review by deepthidoppalapudihmcts — APPROVED** [review]

**Comment by vasudevganesanhmcts** [comment]
closing this as the code is been merged as part of call back url changes

**Pull request closed without merging**
