### PR TITLE
Add Recital text and update docmosis template

### PR DESCRIPTION
**Pull request by karthick-mohanasundaram-HMCTS**
**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-3663

### Related PR ###
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/270
https://github.com/hmcts/civil-service/pull/1317

### Change description ###
1. Add Recital text in Judge request more info screen and update request more info docmosis template.
2. Fix fields disappear on judge request more info screen during navigation back and forth. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
API
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
Template
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
smoke test
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
functional test
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
- [ ] Reset def generalappCCDBranch = "feature/CIV-3663" before merge

**Comment by karthick-mohanasundaram-HMCTS** [comment]
- [ ] Revert jenkins change

**Review by deepthidoppalapudihmcts — APPROVED** [review]

**Comment by vasudevganesanhmcts** [comment]
merging this since the last failure was due to branch indexing and failing to deploy

**Pull request merged**
