### PR TITLE
CIV-3664 Rename Judge Makes decision to Make decision for reusability

### PR DESCRIPTION
**Pull request by karthick-mohanasundaram-HMCTS**
**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [x] Screenshot attached for the Evidence of manual testing
- [x] Functional, Smoke and API tests have been run locally
- [x] Full gradle build and run tests with coverage have been completed (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-3664

### Change description ###

Rename Judge Makes decision to Make decision for reusability

### Testing branch and instruction ###
feature/CIV-3664

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by karthick-mohanasundaram-HMCTS** [comment]
API
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
smoke

image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
functional multiparty
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
function 1v1
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
- [ ] Revert Jenkins

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Review by Azam-Hmcts — APPROVED** [review]

**Review by deepthidoppalapudihmcts — APPROVED** [review]

**Review by MMNycz — APPROVED** [review]

**Review by vasudevganesanhmcts — APPROVED** [review]

**Pull request merged**
