### PR TITLE
CIV-6772 Fix Judge request more info

### PR DESCRIPTION
**Pull request by karthick-mohanasundaram-HMCTS**
**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Screenshot attached for the Evidence of manual testing
- [x] Functional, Smoke and API tests have been run locally
- [x] Full gradle build and run tests with coverage have been completed (if needed)
- [x] DEMO and Code Walk-through

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-6772

### Change description ###

Fix Judge request for more info caching issue

### Testing branch and instruction ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
API

image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
Smoke test failed due to recent code merge in civil service 

image

**Review by deepthidoppalapudihmcts — APPROVED** [review]

**Comment by karthick-mohanasundaram-HMCTS** [comment]
GA CCD changes has to go first as case field has been renamed

https://github.com/hmcts/civil-general-apps-ccd-definition/pull/504/files

- [ ] Merge GA CCD then GA

**Pull request closed without merging**
