### PR TITLE
CIV-3854 Fix document name

### PR DESCRIPTION
**Pull request by karthick-mohanasundaram-HMCTS**
**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [x] Screenshot attached for the Evidence of manual testing
- [ ] Functional, Smoke and API tests have been run locally
- [x] Full gradle build and run tests with coverage have been completed (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-3854

### Change description ###
Fix Direction order file name

### Testing branch and instruction ###

feature/CIV-3854
GA Service
Civil Service CCD
GA CCD

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
Api test

image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
Function test for Directions order
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
Smoke Test
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
functional test
image

**Review by deepthidoppalapudihmcts — APPROVED** [review]

**Review by Azam-Hmcts — APPROVED** [review]

**Pull request merged**
